services:
  php:
    build: ./docker/php
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/app
    working_dir: /app
  web:
    build: ./docker/web
    depends_on:
      - php
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8000:80
    volumes:
      - .:/app
    working_dir: /app
  node:
    build: ./docker/node
    depends_on:
      - php
    environment:
      TZ: Asia/Tokyo
    ports:
      - 5173:5173
    volumes:
      - .:/app
    working_dir: /app
    init: true
    stop_signal: SIGHUP
    entrypoint: []
    command: ["npm","run","dev"]
