services:
  web:
    build: ./docker/web
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/app
    working_dir: /app
  proxy:
    build: ./docker/proxy
    depends_on:
      - web
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8000:80
      - 8443:443
    volumes:
      - .:/app
    working_dir: /app
