services:
  php:
    build: ./docker/php
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/app
    working_dir: /app
  web:
    build: ./docker/web
    depends_on:
      - php
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8000:80
    volumes:
      - .:/app
    working_dir: /app
